package com.cq.sdk.test.dao;

import com.cq.sdk.test.dao.entity.Loginaccount;
import com.cq.sdk.test.dao.entity.LoginaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    long countByExample(LoginaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int deleteByExample(LoginaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int insert(Loginaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int insertSelective(Loginaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    List<Loginaccount> selectByExample(LoginaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    Loginaccount selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") Loginaccount record, @Param("example") LoginaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int updateByExample(@Param("record") Loginaccount record, @Param("example") LoginaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int updateByPrimaryKeySelective(Loginaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    int updateByPrimaryKey(Loginaccount record);
}