package com.cq.sdk.test.dao.entity;

import java.util.Date;

public class Loginaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.pid
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.accountName
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String accountname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.password
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.loginStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String loginstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.accStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String accstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.loginSource
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String loginsource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.userToken
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String usertoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.loginChannel
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String loginchannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.remark
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.lockStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String lockstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.unLockTime
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private Date unlocktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.createBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.createAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.modifyBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private String modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoginAccount.modifyAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    private Date modifyat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.pid
     *
     * @return the value of LoginAccount.pid
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.pid
     *
     * @param pid the value for LoginAccount.pid
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.accountName
     *
     * @return the value of LoginAccount.accountName
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.accountName
     *
     * @param accountname the value for LoginAccount.accountName
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.password
     *
     * @return the value of LoginAccount.password
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.password
     *
     * @param password the value for LoginAccount.password
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.loginStatus
     *
     * @return the value of LoginAccount.loginStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getLoginstatus() {
        return loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.loginStatus
     *
     * @param loginstatus the value for LoginAccount.loginStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setLoginstatus(String loginstatus) {
        this.loginstatus = loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.accStatus
     *
     * @return the value of LoginAccount.accStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getAccstatus() {
        return accstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.accStatus
     *
     * @param accstatus the value for LoginAccount.accStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setAccstatus(String accstatus) {
        this.accstatus = accstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.loginSource
     *
     * @return the value of LoginAccount.loginSource
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getLoginsource() {
        return loginsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.loginSource
     *
     * @param loginsource the value for LoginAccount.loginSource
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setLoginsource(String loginsource) {
        this.loginsource = loginsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.userToken
     *
     * @return the value of LoginAccount.userToken
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getUsertoken() {
        return usertoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.userToken
     *
     * @param usertoken the value for LoginAccount.userToken
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setUsertoken(String usertoken) {
        this.usertoken = usertoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.loginChannel
     *
     * @return the value of LoginAccount.loginChannel
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getLoginchannel() {
        return loginchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.loginChannel
     *
     * @param loginchannel the value for LoginAccount.loginChannel
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setLoginchannel(String loginchannel) {
        this.loginchannel = loginchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.remark
     *
     * @return the value of LoginAccount.remark
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.remark
     *
     * @param remark the value for LoginAccount.remark
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.lockStatus
     *
     * @return the value of LoginAccount.lockStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getLockstatus() {
        return lockstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.lockStatus
     *
     * @param lockstatus the value for LoginAccount.lockStatus
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setLockstatus(String lockstatus) {
        this.lockstatus = lockstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.unLockTime
     *
     * @return the value of LoginAccount.unLockTime
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Date getUnlocktime() {
        return unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.unLockTime
     *
     * @param unlocktime the value for LoginAccount.unLockTime
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setUnlocktime(Date unlocktime) {
        this.unlocktime = unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.createBy
     *
     * @return the value of LoginAccount.createBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.createBy
     *
     * @param createby the value for LoginAccount.createBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.createAt
     *
     * @return the value of LoginAccount.createAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.createAt
     *
     * @param createat the value for LoginAccount.createAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.modifyBy
     *
     * @return the value of LoginAccount.modifyBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.modifyBy
     *
     * @param modifyby the value for LoginAccount.modifyBy
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setModifyby(String modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoginAccount.modifyAt
     *
     * @return the value of LoginAccount.modifyAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Date getModifyat() {
        return modifyat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoginAccount.modifyAt
     *
     * @param modifyat the value for LoginAccount.modifyAt
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setModifyat(Date modifyat) {
        this.modifyat = modifyat;
    }
}