package com.cq.sdk.test.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginaccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public LoginaccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Long value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Long value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Long value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Long value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Long value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Long value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Long> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Long> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Long value1, Long value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Long value1, Long value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNull() {
            addCriterion("accountName is null");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNotNull() {
            addCriterion("accountName is not null");
            return (Criteria) this;
        }

        public Criteria andAccountnameEqualTo(String value) {
            addCriterion("accountName =", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotEqualTo(String value) {
            addCriterion("accountName <>", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThan(String value) {
            addCriterion("accountName >", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThanOrEqualTo(String value) {
            addCriterion("accountName >=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThan(String value) {
            addCriterion("accountName <", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThanOrEqualTo(String value) {
            addCriterion("accountName <=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLike(String value) {
            addCriterion("accountName like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotLike(String value) {
            addCriterion("accountName not like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameIn(List<String> values) {
            addCriterion("accountName in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotIn(List<String> values) {
            addCriterion("accountName not in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameBetween(String value1, String value2) {
            addCriterion("accountName between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotBetween(String value1, String value2) {
            addCriterion("accountName not between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("`password` is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("`password` is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("`password` =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("`password` <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("`password` >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("`password` >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("`password` <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("`password` <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("`password` like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("`password` not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("`password` in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("`password` not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("`password` between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("`password` not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andLoginstatusIsNull() {
            addCriterion("loginStatus is null");
            return (Criteria) this;
        }

        public Criteria andLoginstatusIsNotNull() {
            addCriterion("loginStatus is not null");
            return (Criteria) this;
        }

        public Criteria andLoginstatusEqualTo(String value) {
            addCriterion("loginStatus =", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusNotEqualTo(String value) {
            addCriterion("loginStatus <>", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusGreaterThan(String value) {
            addCriterion("loginStatus >", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusGreaterThanOrEqualTo(String value) {
            addCriterion("loginStatus >=", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusLessThan(String value) {
            addCriterion("loginStatus <", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusLessThanOrEqualTo(String value) {
            addCriterion("loginStatus <=", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusLike(String value) {
            addCriterion("loginStatus like", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusNotLike(String value) {
            addCriterion("loginStatus not like", value, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusIn(List<String> values) {
            addCriterion("loginStatus in", values, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusNotIn(List<String> values) {
            addCriterion("loginStatus not in", values, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusBetween(String value1, String value2) {
            addCriterion("loginStatus between", value1, value2, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andLoginstatusNotBetween(String value1, String value2) {
            addCriterion("loginStatus not between", value1, value2, "loginstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusIsNull() {
            addCriterion("accStatus is null");
            return (Criteria) this;
        }

        public Criteria andAccstatusIsNotNull() {
            addCriterion("accStatus is not null");
            return (Criteria) this;
        }

        public Criteria andAccstatusEqualTo(String value) {
            addCriterion("accStatus =", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusNotEqualTo(String value) {
            addCriterion("accStatus <>", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusGreaterThan(String value) {
            addCriterion("accStatus >", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusGreaterThanOrEqualTo(String value) {
            addCriterion("accStatus >=", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusLessThan(String value) {
            addCriterion("accStatus <", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusLessThanOrEqualTo(String value) {
            addCriterion("accStatus <=", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusLike(String value) {
            addCriterion("accStatus like", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusNotLike(String value) {
            addCriterion("accStatus not like", value, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusIn(List<String> values) {
            addCriterion("accStatus in", values, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusNotIn(List<String> values) {
            addCriterion("accStatus not in", values, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusBetween(String value1, String value2) {
            addCriterion("accStatus between", value1, value2, "accstatus");
            return (Criteria) this;
        }

        public Criteria andAccstatusNotBetween(String value1, String value2) {
            addCriterion("accStatus not between", value1, value2, "accstatus");
            return (Criteria) this;
        }

        public Criteria andLoginsourceIsNull() {
            addCriterion("loginSource is null");
            return (Criteria) this;
        }

        public Criteria andLoginsourceIsNotNull() {
            addCriterion("loginSource is not null");
            return (Criteria) this;
        }

        public Criteria andLoginsourceEqualTo(String value) {
            addCriterion("loginSource =", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceNotEqualTo(String value) {
            addCriterion("loginSource <>", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceGreaterThan(String value) {
            addCriterion("loginSource >", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceGreaterThanOrEqualTo(String value) {
            addCriterion("loginSource >=", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceLessThan(String value) {
            addCriterion("loginSource <", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceLessThanOrEqualTo(String value) {
            addCriterion("loginSource <=", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceLike(String value) {
            addCriterion("loginSource like", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceNotLike(String value) {
            addCriterion("loginSource not like", value, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceIn(List<String> values) {
            addCriterion("loginSource in", values, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceNotIn(List<String> values) {
            addCriterion("loginSource not in", values, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceBetween(String value1, String value2) {
            addCriterion("loginSource between", value1, value2, "loginsource");
            return (Criteria) this;
        }

        public Criteria andLoginsourceNotBetween(String value1, String value2) {
            addCriterion("loginSource not between", value1, value2, "loginsource");
            return (Criteria) this;
        }

        public Criteria andUsertokenIsNull() {
            addCriterion("userToken is null");
            return (Criteria) this;
        }

        public Criteria andUsertokenIsNotNull() {
            addCriterion("userToken is not null");
            return (Criteria) this;
        }

        public Criteria andUsertokenEqualTo(String value) {
            addCriterion("userToken =", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenNotEqualTo(String value) {
            addCriterion("userToken <>", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenGreaterThan(String value) {
            addCriterion("userToken >", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenGreaterThanOrEqualTo(String value) {
            addCriterion("userToken >=", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenLessThan(String value) {
            addCriterion("userToken <", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenLessThanOrEqualTo(String value) {
            addCriterion("userToken <=", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenLike(String value) {
            addCriterion("userToken like", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenNotLike(String value) {
            addCriterion("userToken not like", value, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenIn(List<String> values) {
            addCriterion("userToken in", values, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenNotIn(List<String> values) {
            addCriterion("userToken not in", values, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenBetween(String value1, String value2) {
            addCriterion("userToken between", value1, value2, "usertoken");
            return (Criteria) this;
        }

        public Criteria andUsertokenNotBetween(String value1, String value2) {
            addCriterion("userToken not between", value1, value2, "usertoken");
            return (Criteria) this;
        }

        public Criteria andLoginchannelIsNull() {
            addCriterion("loginChannel is null");
            return (Criteria) this;
        }

        public Criteria andLoginchannelIsNotNull() {
            addCriterion("loginChannel is not null");
            return (Criteria) this;
        }

        public Criteria andLoginchannelEqualTo(String value) {
            addCriterion("loginChannel =", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelNotEqualTo(String value) {
            addCriterion("loginChannel <>", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelGreaterThan(String value) {
            addCriterion("loginChannel >", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelGreaterThanOrEqualTo(String value) {
            addCriterion("loginChannel >=", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelLessThan(String value) {
            addCriterion("loginChannel <", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelLessThanOrEqualTo(String value) {
            addCriterion("loginChannel <=", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelLike(String value) {
            addCriterion("loginChannel like", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelNotLike(String value) {
            addCriterion("loginChannel not like", value, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelIn(List<String> values) {
            addCriterion("loginChannel in", values, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelNotIn(List<String> values) {
            addCriterion("loginChannel not in", values, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelBetween(String value1, String value2) {
            addCriterion("loginChannel between", value1, value2, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andLoginchannelNotBetween(String value1, String value2) {
            addCriterion("loginChannel not between", value1, value2, "loginchannel");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andLockstatusIsNull() {
            addCriterion("lockStatus is null");
            return (Criteria) this;
        }

        public Criteria andLockstatusIsNotNull() {
            addCriterion("lockStatus is not null");
            return (Criteria) this;
        }

        public Criteria andLockstatusEqualTo(String value) {
            addCriterion("lockStatus =", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusNotEqualTo(String value) {
            addCriterion("lockStatus <>", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusGreaterThan(String value) {
            addCriterion("lockStatus >", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusGreaterThanOrEqualTo(String value) {
            addCriterion("lockStatus >=", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusLessThan(String value) {
            addCriterion("lockStatus <", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusLessThanOrEqualTo(String value) {
            addCriterion("lockStatus <=", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusLike(String value) {
            addCriterion("lockStatus like", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusNotLike(String value) {
            addCriterion("lockStatus not like", value, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusIn(List<String> values) {
            addCriterion("lockStatus in", values, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusNotIn(List<String> values) {
            addCriterion("lockStatus not in", values, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusBetween(String value1, String value2) {
            addCriterion("lockStatus between", value1, value2, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andLockstatusNotBetween(String value1, String value2) {
            addCriterion("lockStatus not between", value1, value2, "lockstatus");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeIsNull() {
            addCriterion("unLockTime is null");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeIsNotNull() {
            addCriterion("unLockTime is not null");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeEqualTo(Date value) {
            addCriterion("unLockTime =", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeNotEqualTo(Date value) {
            addCriterion("unLockTime <>", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeGreaterThan(Date value) {
            addCriterion("unLockTime >", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeGreaterThanOrEqualTo(Date value) {
            addCriterion("unLockTime >=", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeLessThan(Date value) {
            addCriterion("unLockTime <", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeLessThanOrEqualTo(Date value) {
            addCriterion("unLockTime <=", value, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeIn(List<Date> values) {
            addCriterion("unLockTime in", values, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeNotIn(List<Date> values) {
            addCriterion("unLockTime not in", values, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeBetween(Date value1, Date value2) {
            addCriterion("unLockTime between", value1, value2, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andUnlocktimeNotBetween(Date value1, Date value2) {
            addCriterion("unLockTime not between", value1, value2, "unlocktime");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("createBy =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("createBy <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("createBy >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("createBy >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("createBy <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("createBy <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("createBy like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("createBy not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("createBy in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("createBy not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("createBy between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("createBy not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNull() {
            addCriterion("createAt is null");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNotNull() {
            addCriterion("createAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateatEqualTo(Date value) {
            addCriterion("createAt =", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotEqualTo(Date value) {
            addCriterion("createAt <>", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThan(Date value) {
            addCriterion("createAt >", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThanOrEqualTo(Date value) {
            addCriterion("createAt >=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThan(Date value) {
            addCriterion("createAt <", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThanOrEqualTo(Date value) {
            addCriterion("createAt <=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatIn(List<Date> values) {
            addCriterion("createAt in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotIn(List<Date> values) {
            addCriterion("createAt not in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatBetween(Date value1, Date value2) {
            addCriterion("createAt between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotBetween(Date value1, Date value2) {
            addCriterion("createAt not between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNull() {
            addCriterion("modifyBy is null");
            return (Criteria) this;
        }

        public Criteria andModifybyIsNotNull() {
            addCriterion("modifyBy is not null");
            return (Criteria) this;
        }

        public Criteria andModifybyEqualTo(String value) {
            addCriterion("modifyBy =", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotEqualTo(String value) {
            addCriterion("modifyBy <>", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThan(String value) {
            addCriterion("modifyBy >", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyGreaterThanOrEqualTo(String value) {
            addCriterion("modifyBy >=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThan(String value) {
            addCriterion("modifyBy <", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLessThanOrEqualTo(String value) {
            addCriterion("modifyBy <=", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyLike(String value) {
            addCriterion("modifyBy like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotLike(String value) {
            addCriterion("modifyBy not like", value, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyIn(List<String> values) {
            addCriterion("modifyBy in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotIn(List<String> values) {
            addCriterion("modifyBy not in", values, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyBetween(String value1, String value2) {
            addCriterion("modifyBy between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifybyNotBetween(String value1, String value2) {
            addCriterion("modifyBy not between", value1, value2, "modifyby");
            return (Criteria) this;
        }

        public Criteria andModifyatIsNull() {
            addCriterion("modifyAt is null");
            return (Criteria) this;
        }

        public Criteria andModifyatIsNotNull() {
            addCriterion("modifyAt is not null");
            return (Criteria) this;
        }

        public Criteria andModifyatEqualTo(Date value) {
            addCriterion("modifyAt =", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatNotEqualTo(Date value) {
            addCriterion("modifyAt <>", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatGreaterThan(Date value) {
            addCriterion("modifyAt >", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatGreaterThanOrEqualTo(Date value) {
            addCriterion("modifyAt >=", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatLessThan(Date value) {
            addCriterion("modifyAt <", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatLessThanOrEqualTo(Date value) {
            addCriterion("modifyAt <=", value, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatIn(List<Date> values) {
            addCriterion("modifyAt in", values, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatNotIn(List<Date> values) {
            addCriterion("modifyAt not in", values, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatBetween(Date value1, Date value2) {
            addCriterion("modifyAt between", value1, value2, "modifyat");
            return (Criteria) this;
        }

        public Criteria andModifyatNotBetween(Date value1, Date value2) {
            addCriterion("modifyAt not between", value1, value2, "modifyat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LoginAccount
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 13 14:10:43 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LoginAccount
     *
     * @mbg.generated Tue Sep 13 14:10:43 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}